version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=socialnetwork
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      - social_network

  redis:
    image: 'redis:7'
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
    networks:
      - social_network

  auth:
    container_name: auth_service
    build: ./auth/
    ports:
      - "8080:8080"
    restart: always
    environment:
      DB_PORT: "5432"
      DB_HOST: "db"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres"
      DB_NAME: "socialnetwork"
      RD_HOST: "redis"
      RD_PORT: "6379"
      JWT_KEY: RtaW4iLCJJc3N
      PORT: "8080"
    depends_on:
      - redis
      - db
    networks:
      - social_network

  chat:
    container_name: chat_service
    build: ./chat/
    ports:
      - "8081:8081"
    restart: always
    environment:
      DB_PORT: "5432"
      DB_HOST: "db"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres"
      DB_NAME: "socialnetwork"
      RD_HOST: "redis"
      RD_PORT: "6379"
      PORT: "8081"
      AUTH_URL: "http://auth:8080"
    depends_on:
      - redis
      - db
    networks:
      - social_network

volumes:
  db:
    driver: local
  redis:
    driver: local

networks:
  social_network: